#!/bin/sh
# clock -- big clock on a text screen.
# Author: Luis Colorado <luiscoloradourcola@gmail.com>
# Date: Sun Mar 25 12:46:44 EEST 2018

DATE=/bin/date
ECHO=/bin/echo
SLEEP=/bin/sleep
WC=/usr/bin/wc


[ -z "$1" ] || \
while read name DELAY FORMAT
do
	[ "$name" = "$1" ] && break
done <<EOF
time		0.1	%X
short		2	%H:%M
w_timezone	0.2	%X %Z
unix		0.2	%s
date		0.2	%x %a%n%X %Z
EOF

if [ -z "$1" ]
then
	FORMAT="w%W-j%j%n%x %a%n%X %Z"
	DELAY="0.1"
else if [ -z "$name" ]
	then
		FORMAT="$1"
		DELAY="1"
	fi
fi

OD=""
while true
do
	D="$(${DATE} "+${FORMAT}")"
	if [ "$D" != "$OD" ]
	then
		[ -z "$OD" ] || ${ECHO} -n "[${L}A"
		O="$(${ECHO} "$D" | banner -f | sed '1s/^/[32m/
		  							 $s/$/[m/
									 s/#/[36m&/
									 s/|$/[32m|/
									 s/#/O/g')"
		L="$(${ECHO} "$O" | ${WC} -l | sed 's/[ 	]*//')"
		${ECHO} "$O" | sed 's/$/[K/'
	else
		${SLEEP} "$DELAY"
	fi
	OD=$D
done
